# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OpensearchCli < Formula
  desc "A full-featured command line interface (CLI) for OpenSearch."
  homepage "https://github.com/opensearch-project/opensearch-cli"
  version "opensearch-cli_1.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-clients/opendistro-cli/opendistro-odfe-cli-1.1.0-macos-x64.zip"
    sha256 "6950edfe6720e9b2f89f3210270f1c3ad219ce2fbe60b2024ea682f43b31b3d3"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/VijayanB/es-cli/releases/download/v1.1.0/opensearch-cli_Darwin_arm64.tar.gz"
    # sha256 "f5cd1f80a1a592f0e8c8cc5f5d93b23bb260b073f1a175bd2861cb45db6da585"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-clients/opendistro-cli/opendistro-odfe-cli-1.1.0-linux-x64.zip"
    # sha256 "fb4f694a5e3e8047891192ecdf181a281c74136b5c130b126e92b1522b46d5d6"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/VijayanB/es-cli/releases/download/v1.1.0/opensearch-cli_Linux_armv6.tar.gz"
    # sha256 "42b04ec539ab5c7754731033d1eafcadea4336ea1bd293fc670b095efcf3356d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://d3g5vo6xdbdb9a.cloudfront.net/downloads/elasticsearch-clients/opendistro-cli/opendistro-odfe-cli-1.1.0-linux-arm64.zip"
    # sha256 "5c41ef2f52285f4ad0408724cd074b85a03bb929af513ed7599a2f9d1b13b695"
  end

  def install
    bin.install "odfe-cli"
  end
end
